# image name --> Cusotm webapp
# image version --> nginx:1.14.2
# Ports on 80 
#---------------------------------------------------------------#

apiVersion: v1
kind: Pod
metadata:
  name: webapp01
  labels:
    env: dev 
    department: HR 
spec:
  containers:
  - name: custom-webapp
    image: nginx:1.14.2
    ports:
    - containerPort: 80
