---
apiVersion: v1
kind: Service
metadata: 
  name: my-loadbalancer-service
  labels:
    env: dev
spec:
  type: LoadBalancer
  selector:
    app: demo-deploy
  ports:
    - protocol: TCP
      port: 3200       # ClusterIP Port
      targetPort: 80   # Service Port on POD 
      nodePort: 30010  # NodePort 
