---
apiVersion: v1
kind: Service
metadata:
  name: my-clusterip-service
  labels:
    env: dev
spec:
  type: ClusterIP  # Default is ClusterIP, no need to mention
  selector:
    app: demo-deploy
  ports:
    - name: http
      port: 8080
      targetPort: 80
      protocol: TCP
