---
apiVersion: v1
kind: Service
metadata:
  name: my-nodeport-service
  labels:
    env: dev
spec:
  type: NodePort
  selector:
    app: demo-deploy
  ports:
    - targetPort: 80
      port: 80
      nodePort: 32000
