---
apiVersion: v1
kind: Pod
metadata:
  name: injec-cm-from-file-to-pod
  labels:
    purpose: test-cm-from-a-file-use-volume
spec:
  volumes:
  - configMap:
      name: cm-from-file
    name: vol1
  containers:
  - name: test-cm
    image: nginx
    volumeMounts:
    - name: vol1
      mountPath: /var/tmp/mount1
