---
apiVersion: v1
kind: Pod
metadata:
  name: cmd-arg-example
  labels:
    purpose: demo-command-argument
spec:
  containers:
  - name: command-arg-demo-container
    image: debian
    command: ["printenv"]
    args: ["HOSTNAME", "KUBERNETES_PORT"]
  restartPolicy: OnFailure
