---
apiVersion: v1
kind: Pod
metadata:
  name: run-script-in-bash
  labels:
    purpose: run-script-command-in-bash
spec:
  containers:
  - name: scrip-in-shell
    image: debian
    command: ["/bin/sh"]
    args: ["-c", "while true; do echo hello; sleep 10;done"]
