---
apiVersion: v1
kind: Pod
metadata:
  name: use-secret1
  labels:
    purpose: test-secret1-in-pod
spec:
  containers:
  - name: test-pod
    image: nginx
    ports:
      - containerPort: 8080
    envFrom:
      - secretRef:
          name: secret1
