---
apiVersion: v1
kind: Pod
metadata:
  name: use-secret1-from-literal-method2
  labels:
    purpose: test-secret1-in-pod
spec:
  containers:
  - name: test-pod
    image: nginx
    ports:
      - containerPort: 8081
    env:
      - name: DB_passwd
        valueFrom:
          secretKeyRef:
            name: secret1
            key: key1
