---
apiVersion: v1
kind: Pod
metadata:
  name: use-secret3-declarative_secret
  labels:
    purpose: test-secret3-in-pod
spec:
  containers:
  - name: test-pod
    image: nginx
    ports:
      - containerPort: 8083
    envFrom:
      - secretRef:
          name: secret3
