---
apiVersion: v1
kind: Pod
metadata:
  name: use-secret1-fromfile-volume
  labels:
    purpose: test-secret2-in-pod
spec:
  volumes:
  - name: secret-volume
    secret:
      secretName: secret2
  containers:
  - name: test-pod
    image: nginx
    ports:
      - containerPort: 8084
    volumeMounts:
    - name: secret-volume
      mountPath: /var/tmp/mount1

